[build]
  base = "frontend-app"
  publish = "dist"
  command = "npm run web:build"

[build.environment]
  NODE_VERSION = "18"

# 개발 환경 설정
[context.develop]
  command = "NODE_ENV=development npm run web:build"

[context.develop.environment]
  NODE_ENV = "development"

# 프로덕션 환경 설정
[context.production]
  command = "NODE_ENV=production npm run web:build"

[context.production.environment]
  NODE_ENV = "production"

# 브랜치별 배포 설정
[context.branch-deploy]
  command = "npm run web:build"

# 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 리다이렉트 설정 (SPA용)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 404 페이지
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200