version: 1.0
identifier: focuz-ios
actions:
  - name: Archive
    action: build
    platform: iOS
    scheme: FOCUZ
    pre-xcodebuild:
        script: |
    chmod +x ./ci_scripts/ci_pre_xcodebuild.sh
    ./ci_scripts/ci_pre_xcodebuild.sh
